### PR TITLE
allow usage of skip parameter in pouchdb adapter queries

### PR DESCRIPTION
**Pull request by akatov**

### CODE REVIEW

**Comment by broerse** [comment]
@afinne can you that a look at this PR ?

**Comment by broerse** [comment]
@akatov can you resolve the conflicts.

**Comment by broerse** [comment]
@akatov do you have time to resolve the conflicts?

**Comment by afinne** [comment]
Pinging @akatov

**Comment by akatov** [comment]
sorry, got sidelined...
thanks for reminding me!

**Comment by broerse** [comment]
@akatov Just merged the move to the new Travis. If you fix this perhaps we can release a new version.

**Comment by broerse** [comment]
@akatov I can't wait for this so it has to be merged in the next version. Will release this version today.

**Comment by akatov** [comment]
@broerse rebased

**Comment by broerse** [comment]
Thanks!

**Pull request merged**
