### PR TITLE
Fix some jobs on Travis Trusty

### PR DESCRIPTION
**Pull request by backspace**
This is a pretty hackish solution to [this problem](https://github.com/ember-cli/ember-try/issues/125), also discussed [here](https://github.com/ember-cli/ember-try/issues/133): `ember-try` uses the presence of a `yarn` command to determine whether to `yarn install`. Something was [going wrong with the `yarn install`](https://travis-ci.org/pouchdb-community/ember-pouch/jobs/257985277#L3444-L3454) on the `ember-release` and `ember-beta` scenarios.

This fixes those scenarios but then breaks the ones before them, the inverse of what was happening!

I’m going to ask over on the `ember-try` thread about whether it’s possible to bypass Yarn more elegantly. I’ll also see if I can override Ember CLI’s built-in `ember-try` version with an older one that doesn’t use Yarn.

### CODE REVIEW

**Comment by backspace** [comment]
Adding an older `ember-try` to the `package.json` has fixed the problems on Trusty because 0.2.11 doesn’t try to use `yarn install`. I’m not a huge fan of this workaround, hopefully my query in `ember-try` will yield another possibility.

**Comment by backspace** [comment]
Incidentally, Trusty has PhantomJS 2.0.0 installed, so we could perhaps abandon the `bower.json` file entirely because I believe it doesn’t need the polyfill.

Or should we switch to headless Chrome or Firefox?

**Comment by broerse** [comment]
I have seen somewhere that Ember will swap PhantomJS for headless Crome in version 16 but can find where I have seen that. So I think switching to headless Chrome is the future anyway. We could do that. See also: https://embermap.com/notes/59-ember-tests-with-headless-chrome

**Comment by broerse** [comment]
It will be in ember-cli 15.0 See https://github.com/ember-cli/ember-cli/pull/7148

**Comment by backspace** [comment]
ah, not too far away! Maybe it makes sense to just wait for that release and do it all at once.

I have a [preliminary PR on `ember-try`](https://github.com/ember-cli/ember-try/pull/138) to stop trying to use Yarn when there’s no lockfile, I’ll proceed with this fix once that issue is fixed.

**Comment by broerse** [comment]
@backspace now your PR is merged do we wait for ember-cli 15.0 or can this be fixed now?

**Comment by backspace** [comment]
I don’t think a new `ember-try` version has been released yet, so it won’t be included in Ember CLI, right? We could override the version but that seems annoying…???

**Comment by broerse** [comment]
I assumed it was released also. Don't overwrite the version for this. We will wait. Perhaps fix this together with https://github.com/pouchdb-community/ember-pouch/pull/110

**Comment by backspace** [comment]
A new version of `ember-try` was released, so I continued with this. I ended up just updating Ember CLI, which brought along the new `.travis.yml` blueprint that switches to Trusty. I removed the Bower thing for the PhantomJS `Object.assign` polyfill.

What do you think, @broerse or interested parties? This grew beyond what I originally started the PR for, I can adjust as desired.

**Comment by broerse** [comment]
Looking good @backspace !  I think no need to adjust this. But can you squash this so we I can see more clear what will be merged?

**Comment by backspace** [comment]
GitHub lets you squash and merge from a PR now:

image

So whatever you see on the [Files changed](https://github.com/pouchdb-community/ember-pouch/pull/187/files) tab is what the commit will look like. But if you want, I can still squash locally.

**Comment by broerse** [comment]
I will take the change ;-)

**Comment by jlami** [comment]
I'm affraid the changes to the ember-try config have removed the ember-data versions.
See here: https://travis-ci.org/pouchdb-community/ember-pouch/jobs/298350042#L3176
This is the job with ember 2.16.2, but ember-data is not changed.

I think ember-data still needs to be added to the ember-try setup like before: https://github.com/pouchdb-community/ember-pouch/pull/187/files#diff-d20f4baf61c4397c467d6218d0ba6a04L25

**Comment by backspace** [comment]
eep sorry about that, I can look into it tomorrow

**Pull request merged**
