### PR TITLE
clean up db changes listener

### PR DESCRIPTION
**Pull request by akatov**
I had issues where in acceptance tests an adapter from the previous run would fire on changes to the database of an adapter from the current run...

### CODE REVIEW

**Comment by jlami** [comment]
That sounds like an excellent catch!

**Comment by broerse** [comment]
@jlami Do you want to merge this in beta.3 ?

**Comment by jlami** [comment]
This can go in beta, or in master, either way is fine.

**Comment by broerse** [comment]
@akatov Thanks! We will release a breaking 5.0.0 but improved version soon.

**Pull request merged**
