### PR TITLE
Ignore same revision changes

### PR DESCRIPTION
**Pull request by jlami**
Possible solution for #188

Will look for a better solution

### CODE REVIEW

**Comment by broerse** [comment]
Should I merge this?

**Comment by jlami** [comment]
Not yet I think, this is a temporary fix to see if this is the way to go. I have an extra issue open on ember-data to see if this is something they can fix.

**Comment by tobiasWenger** [comment]
@jlami Could you find out if it is the way to go? I would like to have this "hack" merged into master.

**Comment by jlami** [comment]
@tobiasWenger Do you have experience with this hack in place. I must admit that I have not tested it as thoroughly as I wanted yet.

**Comment by tobiasWenger** [comment]
@jlami My app is still in the development phase but up to now I did not encounter any problems. I added this hack locally to the newest version (4.3.0) to test it and it seams to work fine.

**Comment by jlami** [comment]
Let's use this then and we will see if there are any problems or if we can even improve on this.

**Comment by tobiasWenger** [comment]
@jlami Many thanks and I really appreciate all of your work. I would be lost without people like you. Keep up the good work!

**Pull request merged**
