### PR TITLE
allow usage of limit parameter in pouchdb adapter queries

### PR DESCRIPTION
**Pull request by akatov**

### CODE REVIEW

**Comment by broerse** [comment]
@akatov Can you add something to the readme about this?

**Comment by akatov** [comment]
sure. will do this and a rebase as well

**Comment by afinne** [comment]
It could be an idea to also include skip?

What we did in our project was:

```
    queryParams = {
      selector: selector
      limit: query.limit ? 100
      skip: query.skip
    }
    queryParams.sort = @_buildSort(query.sort) unless Ember.isEmpty(query.sort)

```

Note, we use coffeescript

**Comment by akatov** [comment]
@afinne good idea! @broerse I'm happy to make another PR for the `skip` parameter

**Comment by akatov** [comment]
see #198 for `skip` parameter

**Comment by broerse** [comment]
@akatov Thanks will merge both today.

**Pull request merged**
